platform :ios, '7.0'

pod 'Mantle', '~> 1.3'
pod 'SSKeychain'
pod 'SVProgressHUD'
pod 'NSDate+TimeAgo'
pod 'SGNavigationProgress'
pod 'CorePlot'
pod 'MRProgress', '~> 0.2'
pod 'HTCopyableLabel'
pod 'UITableView-NXEmptyView'
pod 'PKRevealController'
pod 'NJKWebViewProgress'
pod 'SVWebViewController', :head
pod 'RDVTabBarController'
pod 'Masonry'
pod 'UIView+AutoLayout'
pod 'SLRESTfulCoreData'
pod "MagicalRecord"
pod 'Vertigo'